# Generated by Django 4.2.3 on 2023-07-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_comments_post_alter_comments_id_alter_comments_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
